### ISSUE TITLE
Working Cascadia webscraping example

### ISSUE THREAD

**Issue by hpoit** [Algocircle/Cascadia.jl#12]
https://gist.github.com/hpoit/7c6ce575fc5a4a274ed8c9cb6eab4a19

**Comment by hpoit** [comment]
Strangely the example worked with the deprecated `Requests.jl`

**Comment by hpoit** [comment]
I am guessing `HTTP` took `Requests` place with `HTTP.get`?

**Comment by henry2004y** [comment]
Maybe the example in README.md should be updated accordingly?

**Comment by aviks** [comment]
Yeah, that might be a good idea. Anybody want to send a PR?

**Comment by henry2004y** [comment]
I'll try. This might also be a good chance for me to learn about the PR process.

**Comment by aviks** [comment]
Readme has been updated. fixed by #14
