### ISSUE TITLE
Children selectors

### ISSUE THREAD

**Issue by Nosferican** [Algocircle/Cascadia.jl#13]
What's the status for including child(ren) related selectors?

**Comment by aviks** [comment]
The code is in there, but there is probably an off by one bug somehwere. I haven't had the time to debug it.

**Comment by ChenNingCong** [comment]
Hello everyone here!
@aviks  Recently I spend some time debugging this package and I have made a pull request to fix the children selector. On my computer it passes all the tests. Can you review it?

**Comment by aviks** [comment]
Thanks @ChenNingCong 

Fixed by https://github.com/Algocircle/Cascadia.jl/commit/97d81f1dcb76f2b710d31dde9babdf9d25a8d7e9
