### ISSUE TITLE
Tag ?

### ISSUE THREAD

**Issue by lassepe** [Algocircle/Cascadia.jl#18]
It may be nice to create a tag with Gumbo 0.8 compat. Currently, Cascadia 0.4.0 is checked out if Gumbo 0.8 is already loaded since Cascadia 0.4.0 (still with REQUIRE file) does not have any version bounds while Cascadia 0.5.0 is has
```
[compat]
Gumbo = "0.5, 0.7"
```

**Comment by aviks** [comment]
Done https://github.com/JuliaRegistries/General/pull/16717
