### ISSUE TITLE
Scrap TEXT data from web page

### ISSUE THREAD

**Issue by raman-maker** [Algocircle/Cascadia.jl#28]
Please see this https://discourse.julialang.org/t/web-scraping-of-gcn-nasa-circulars-text/100809/6 to understand issue.
I have also opened same issue in Gumbo.jl github.

**Comment by aviks** [comment]
This kind of usage question is best asked on discourse. Your post has plenty of responses that gives you ideas to move forward. There is no bug or issue in Cascadia that we can fix here.
